# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: SQL
    steps:
    - script: |
        echo Build SQL.
      displayName: 'Run a SQL Build-line script'

  - job: API
    dependsOn: SQL
    steps:
    - script: |
        echo Build Back.
      displayName: 'Run a Back Build-line script'

  - job: Front
    dependsOn: API
    steps:
    - script: |
        echo Build Front.
      displayName: 'Run a Font Build-line script'

