# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage:  Build
    jobs:
    - job: BuildSql
      steps:
        - bash: echo Bash SQL
    - job: BuildApi
      steps:
        - bash: echo Bash Api
    - job: BuildFront
      steps:
        - bash: echo Bash Front

  - stage:  DevDeploy
    jobs:
    - job: DeployDev
      steps:
      - bash: echo Dev Deployment

  - stage:  ProdDeploy
    jobs:
    - job: DeployDev
      steps:
      - bash: echo Prod Deployment
