version: '3.7'

services:
  front:
    restart: always
    build: 
      context: ./front-end/.
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

  #  image: <Docker Hub user name>/front:<version> # Maybe I will switch to this type
  back:
    build:
      context: ./back-end/backapp/.
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    restart: always
    # depends_on:
    #   - db-mongo
      # - persistance

#+    image: <Docker Hub user name>/back:<version> # Same

  # persistance:
  #   image: firebase:local
  #   hostname: "firebase-local"
  #   build:
  #     context: ./firebase/.
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./firebase/.:/firebase
  #     # `pwd`:/firebase
  #   ports:
  #     - '443:443'
  #     - '5000:5000'
  #     - '9000:9000'
  #   # command: firebase-server -a 0.0.0.0 -p 5000 -f /app/server/data.json -r /app/server/rules.json
  #   # command: firebase serve --only database -p 9000
  #   restart: always

  # db-mongo:
  #   image: mongo
  #   container_name: mongodb
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: root
